root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"

include_ext = ["go"]
exclude_dir = [
    "tmp",
    "vendor",
    ".git",
]

delay = 500

stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"