version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.5
    container_name: agro-postgis
    environment:
      POSTGRES_DB: agrodb
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
