POST http://localhost:8080/api/commands/
Content-Type: application/json

{
  "command": "agronomy.create_crop",
  "data": {
    "name": "shalasawdadawdawdh",
    "category": "awdawdawdaw"
  }
}

###

POST http://localhost:8080/api/queries/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "query": "agronomy.get_crop",
  "data": {}
}

###

POST http://{{host}}/api/queries/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "query": "agronomy.list_crops",
  "data": {
    "categories": ["овощные", "клубнеплоды"]
  }
}

###
POST http://{{host}}/api/commands/
Content-Type: application/json
Authorization: Bearer {{token}}

{"command":"agronomy.create_variety","data":{"cropId":"2a54abf6-3fb5-47e3-8424-392cb489f80c","name":"Шантане","profile":{"maturity":{},"spacing":{}},"characteristics":{}}}


###

POST http://localhost:8080/api/queries/
Content-Type: application/json

{
  "query": "GetCurrentFarm",
  "data": {
    "id": "tomato"
  }
}