POST http://{{host}}/auth/register
Content-Type: application/json

{"email":"dev@agro.com", "username": "awdawd","password":"admin123"}

###
POST http://{{host}}/auth/login
Content-Type: application/json

{
"email": "admin@example.com",
"password": "admin123"
}



###
POST http://{{host}}/api/queries/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJvcmdhbml6YXRpb25faWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJvcmdfcm9sZSI6Im93bmVyIiwiaXNzIjoiaG9tZS1zZXJ2aWNlcyIsImV4cCI6MTc3NzQwNDA3MSwiaWF0IjoxNzc3MzE3NjcxfQ.rzgUSDRWd3dmAKpdHcu-LSJ5asRxPwz16ooulp-KkqI

{
  "query": "Me",
  "data": {
  }
}

###
POST http://localhost:8080/api/commands/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJvcmdhbml6YXRpb25faWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEiLCJvcmdfcm9sZSI6Im93bmVyIiwiaXNzIjoiaG9tZS1zZXJ2aWNlcyIsImV4cCI6MTc3NzM5ODI5OSwiaWF0IjoxNzc3MzExODk5fQ.v8uQ1b_VWIZcK1uXnwa8vFBGSJzAWFO6-ntVWJZ01bM

{
  "command": "CreateOrganization",
  "data": {
    "name": "огород"
  }
}

