POST http://localhost:8080/api/commands/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


{
  "command": "spatial.create_production_unit",
  "data": {
    "name": "shalasawdadawdawdh",
    "farmId": "awdawdawdaw",
    "type": "FIELD"
  }
}

###

POST http://{{host}}/api/commands/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "command": "spatial.configure_production_unit",
  "data": {
    "id": "58a6c781-a659-4576-bc20-12b361f9f145",
    "schema": [
      {
        "id": "7d7f6ee8-6534-4b94-95d3-4db06a274e37",
        "type": "bed",
        "x": 0.6,
        "y": 0.2,
        "width": 3,
        "length": 0.8,
        "name": "Грядка 1",
        "code": "B- 1"
      },
      {
        "id": "5a5d8d3d-7fcf-482e-9f86-34ca74f141cb",
        "type": "bed",
        "x": 1.8,
        "y": 1.9,
        "width": 3,
        "length": 0.8,
        "name": "Грядка 2",
        "code": "B- 2"
      }
    ]
  }
}
###

POST http://localhost:8080/api/queries/
Content-Type: application/json

{
  "query": "GetCurrentFarm",
  "data": {
    "id": "tomato"
  }
}