POST http://localhost:8080/api/commands/
Content-Type: application/json

{
  "command": "spatial.create_production_unit",
  "data": {
    "name": "shalasawdadawdawdh",
    "farmId": "awdawdawdaw",
    "type": "FIELD"
  }
}

###

POST http://localhost:8080/api/queries/
Content-Type: application/json

{
  "query": "GetCurrentFarm",
  "data": {
    "id": "tomato"
  }
}